services:
  mongodb:
    image: mongo:7
    container_name: favorite-recipes-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: favorite-recipes
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:

